#!/usr/bin/env python3
"""Read checked-in catalogs only; never fetch, publish or change seed evidence."""
import argparse
from collections import Counter
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
CATALOGS = (
    'chicago-metro-public-resources.json', 'national-public-resources.json',
    'national-community-resources.json', 'national-government-resources.json',
    'state-benefit-resources.json',
)


def family(source_id):
    if source_id == 'cpl': return 'cpl'
    if source_id in ('hrsa', 'hrsa-national'): return 'hrsa'
    if source_id == 'food' or source_id.startswith('vivery-network-'): return 'food-networks'
    if source_id == 'hud-current': return 'hud-counseling'
    if source_id == 'hud-public-housing-authorities': return 'hud-pha'
    if source_id == 'ssa-field-offices': return 'ssa'
    if source_id == 'va-public-offices': return 'va'
    if source_id.startswith('idhs-'): return 'idhs'
    if source_id == 'colorado-wic': return 'colorado-wic'
    return 'provider-pages'


def tally(values):
    return dict(sorted(Counter(values).items()))


def build_inventory(catalogs, policies):
    sources, resources, ids = {}, [], set()
    for filename, catalog in sorted(catalogs.items()):
        for source_id, metadata in catalog['sources'].items():
            if source_id in sources:
                raise ValueError(f'Duplicate source identity: {source_id}')
            if family(source_id) not in policies['families']:
                raise ValueError(f'Missing family policy: {source_id}')
            sources[source_id] = dict(sourceId=source_id, family=family(source_id),
                                      catalog=filename, metadata=metadata, records=[])
        for row in catalog['resources']:
            if row['id'] in ids:
                raise ValueError(f'Duplicate resource identity: {row["id"]}')
            if row['sourceId'] not in catalog['sources']:
                raise ValueError(f'Missing source for {row["id"]}')
            ids.add(row['id'])
            resource = dict(row, category='library' if row['sourceId'] == 'cpl' else row['category'])
            sources[row['sourceId']]['records'].append(resource)
            resources.append(resource)
    rows = []
    for source_id, source in sorted(sources.items()):
        records = source.pop('records')
        source.update(recordCount=len(records), states=tally(r['state'] for r in records),
                      categories=tally(r['category'] for r in records),
                      services=tally(s for r in records for s in r.get('services', [])),
                      sampleResourceIds=sorted(r['id'] for r in records)[:2],
                      findings=policies.get('sourceFindings', {}).get(source_id, []))
        rows.append(source)
    closed = sum(bool(re.search('closed until further notice', r['usualHours'], re.I)) for r in resources)
    return dict(schemaVersion=1, basis='checked-in-catalogs-not-live-state',
                policyReviewedAt=policies['reviewedAt'], catalogCounts={n: len(c['resources']) for n, c in sorted(catalogs.items())},
                recordCount=len(resources), sourceCount=len(sources),
                excludedClosedCount=closed, states=tally(r['state'] for r in resources),
                categories=tally(r['category'] for r in resources),
                families=tally(s['family'] for s in rows),
                coverageMeaning='Presence in a snapshot; missing records do not establish absence of services.',
                policies=policies['families'], sources=rows)


def markdown(report):
    def cell(value):
        return str(value).replace('|', '\\|').replace('\n', ' ')
    lines = ['# Public-source inventory', '',
             'Generated by `python3 scripts/inventory_public_sources.py --format markdown`.', '',
             'This inventories checked-in snapshots, not live records, current service availability or permission to automate. '
             'Policy review date: '+report['policyReviewedAt']+'. See [source onboarding](./source-onboarding.md).', '',
             f"{report['recordCount']:,} records; {report['sourceCount']} source identities; "
             f"{report['excludedClosedCount']} snapshot record(s) excluded by the existing closed-until-further-notice rule. "
             'CPL categories are normalized to library, matching the runtime. Libraries remain opt-in.', '',
             '## Catalog totals', '', '| Catalog | Records |', '| --- | ---: |']
    lines += [f'| `{n}` | {c} |' for n,c in report['catalogCounts'].items()]
    lines += ['', '## Regional snapshot counts', '',
              'Counts include all catalog rows and do not measure complete geographic or service-detail coverage.', '',
              '| State/territory | Records |', '| --- | ---: |']
    lines += [f'| {n} | {c} |' for n,c in report['states'].items()]
    lines += ['', '## Source identities', '',
              'The JSON output retains every original endpoint, hash, publisher/retrieval date, category/service/region count and sample resource ID. '
              'Hashes remain unverified snapshot metadata here; this command cannot attest to original downloaded bytes.', '',
              '| Source | Publisher | Family | Records | Retrieved | Publisher date |', '| --- | --- | --- | ---: | --- | --- |']
    for s in report['sources']:
        m=s['metadata']
        lines.append(f'| `{s["sourceId"]}` | [{cell(m["name"])}]({m["url"]}) | {s["family"]} | {s["recordCount"]} | {m["retrievedAt"]} | {m.get("publishedAt", "unknown")} |')
    lines += ['', '## Metadata findings requiring review', '']
    for s in report['sources']:
        lines += [f'- `{s["sourceId"]}`: {cell(f)}' for f in s['findings']]
    return '\n'.join(lines)+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--format', choices=['json','markdown'], default='json')
    args=parser.parse_args()
    catalogs={name: json.loads((ROOT/'services/api/src/db/seed-data'/name).read_text()) for name in CATALOGS}
    policies=json.loads((ROOT/'docs/data/source-policies.json').read_text())
    report=build_inventory(catalogs,policies)
    print(markdown(report) if args.format=='markdown' else json.dumps(report,ensure_ascii=False,indent=2),end='' if args.format=='markdown' else '\n')


if __name__=='__main__': main()
